# Generated by Django 4.2.1 on 2023-06-13 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('about', models.CharField(max_length=5000)),
                ('image', models.CharField(max_length=5000)),
            ],
        ),
        migrations.CreateModel(
            name='Blinds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=5000)),
                ('about', models.CharField(max_length=5000)),
                ('image', models.CharField(max_length=5000)),
            ],
        ),
        migrations.CreateModel(
            name='Curtains',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=5000)),
                ('about', models.CharField(max_length=5000)),
                ('image', models.CharField(max_length=5000)),
            ],
        ),
        migrations.CreateModel(
            name='Doorlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=5000)),
                ('about', models.CharField(max_length=5000)),
                ('image', models.CharField(max_length=5000)),
            ],
        ),
        migrations.CreateModel(
            name='Sofa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=5000)),
                ('about', models.CharField(max_length=5000)),
                ('image', models.CharField(max_length=5000)),
            ],
        ),
    ]
